### ISSUE TITLE
Recursion

### ISSUE THREAD

**Issue by zsau** [N0taN3rd/Squidwarc#13]
It's not clear from the docs whether `page-same-domain` is supposed to crawl recursively. From my tests it doesn't seem to, but it's possible I'm doing something wrong. If not, then consider this a feature request for recursion.

**Comment by N0taN3rd** [comment]
@zsau Thank you for pointing the unclearness of the docs, I will updating it. 
The current setup is the mod applies to initial seed list then page only for any additional seeds found. 

Is there a particular way that you would like to see the recursion expressed?

Heritrix has the concept of hops 
```xml
<!-- ...but REJECT those more than a configured link-hop-count from start... -->
    <bean class="org.archive.modules.deciderules.TooManyHopsDecideRule">
     <property name="maxHops" value="1"/>
    </bean>
```

**Comment by zsau** [comment]
Perhaps a pluggable "strategy" to determine when to end the crawl would be best, but in my case I don't currently need anything beyond the same-domain restriction. Setting a max # of hops seems reasonable, though.

**Comment by N0taN3rd** [comment]
@zsau this is implemented https://n0tan3rd.github.io/Squidwarc/manual/configuration.html
