### ISSUE TITLE
Support a simple list of URIs

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/Squidwarc#18]
### Are you submitting a **bug report** or a **feature request**?
Feature request.

### What is the current behavior?

Reads JSON list of URIs as input.

### What is the expected behavior?
Also allow a simple CRLF list of URIs

### What's your environment?

N/A

### Other information

Scenario put forth by @ibnesayeed but I can imagine this being useful for others.

**Comment by N0taN3rd** [comment]
this is implemented

**Comment by N0taN3rd** [comment]
see https://n0tan3rd.github.io/Squidwarc/manual/configuration.html
