### ISSUE TITLE
Add docker file

### ISSUE THREAD

**Issue by N0taN3rd** [N0taN3rd/Squidwarc#24]
### Are you submitting a **bug report** or a **feature request**?

feature request

### What is the current behavior?

Create MWE Dockerfile for others to use

**Comment by peterk** [comment]
Check [Dockerfile in warcworker repo](https://github.com/peterk/warcworker/blob/master/worker/Dockerfile) for a possible starting point. Having tested it for a while I am leaning more towards using regular Chrome instead of Chromium though.
