### ISSUE TITLE
Allow crawl config to contain user scripts for a page

### ISSUE THREAD

**Issue by peterk** [N0taN3rd/Squidwarc#25]
### Are you submitting a **bug report** or a **feature request**?

Feature request

### What is the current behavior?

Currently a page is loaded and put into a WARC. It would be great if a crawl config could allow for one or more user script to be run by the crawler after page load. This means a user could specify scrolling and click events (e.g. expand comments) to capture a page even better.

**Comment by N0taN3rd** [comment]
@peterk I have been playing around with a few ways for implementing this feature request.
Are you familiar with [GoogleChrome/puppeteer](https://github.com/GoogleChrome/puppeteer)? 
I am favoring using puppeteer to aid in getting this feature implemented quickly as puppeteer has page scripting capabilities that would take me some time to implement a Squidwarc exclusive version.

For example in light of issue #26, consider the following user script snippet below that extracts and fetches all `srcset` values that exist in the rendered DOM.
```js
module.exports = async function (page) {
  await page.$$eval('*[srcset]', async ss => {
    const noop = () => {}
    const doFetch = url => fetch(url).catch(noop)
    const srcsetSplit = /\s*(\S*\s+[\d.]+[wx]),|(?:\s*,(?:\s+|(?=https?:)))/
    for (let i = 0; i < ss.length; i++) {
      const srcset = ss[i].srcset
      const values = srcset.split(srcsetSplit).filter(Boolean)
      for (let j = 0; j < values.length; j++) {
        const value = values[j].trim()
        if (value.length > 0) {
          const url = value.split(' ')[0]
          await doFetch(url)
        }
      }
    }
  })
}
```
The implementation would be the user (you) would supply a js file that exports a async function(s) like above. 
The function(s) expect a single argument `page` ([puppeteer/Page](https://pptr.dev/#?product=Puppeteer&version=v1.6.2&show=api-class-page)) and all interactions happen that way.

Do you have any thoughts/suggestions about this feature implementation as described above?

**Comment by peterk** [comment]
That sounds like a great idea. I suppose one would like to do generic scripts as the srcset above as well as site specific scripts (e.g. click "See more comments" on a specific website). Maybe it could be possible to have a folder with named scripts available to squidwarc and then only supply the filename in the crawl config?

```javascript
{
  //crawl config settings...
  "scripts": [
    "srcset_images",
    "fb_comments_expander",
    "javascript:module.exports = async function my_custom_oneoff(page) ..."
  ],
//...
}
```

Or did you have other ideas on how to submit the script to the crawl job?

**Comment by N0taN3rd** [comment]
@peterk I agree that the use case for this feature is more generic scripts, apologies for not being clearer in my explanation of the minimal working example.
My inclination for implementation and flexibility for users of the feature would be to, as you suggested, add a `scripts` field in the crawl config that is expected to contain a path to the file to be used (g.e. `/home/usr/someDir/scripts.js` or `./script.js`).

Then the script, whose path is the value of the `scripts` field, would then expose a single function like below in that it does `module.exports = async function...`
```js
const someOtherScript = require('path-to-other-script')

async function anotherScript () { .... }

module.exports = async function (page) {
  await page.evaluate(someOtherScript)
  await page.evaluate(anotherScript)
}
``` 

Squidwarc will then require the file listed in the `script` field and execute the exported function and wait until the promise returned by the function resolves.
Once the promise resolves, the WARC will generated or appended to and Squidwarc will move to the next page.

**Comment by peterk** [comment]
Excellent! I think this will make squidwarc a very powerful tool.

**Comment by N0taN3rd** [comment]
@peterk I am pleased to inform you that this feature is ready for testing / general use :godmode:
However this functionality is still on its own branch(es) until I merge everything (Squidwarc and node-warc impls) into master.
Until then, the docker file excerpt below (modified [peterk/warcworker/worker/Dockerfile#L14-16](https://github.com/peterk/warcworker/blob/413ee7693a67f19a2147722d32c7a61b35a9eb71/worker/Dockerfile#L14-L16)) should get you bootstrapped and ready to use the feature today.  
```dockerfile
RUN git clone https://github.com/N0taN3rd/Squidwarc.git
WORKDIR Squidwarc
RUN git checkout puppeteerCrawler && git submodule init && git submodule update
RUN npm install && cd node-warc && npm install && cd ..
```
Please note the git commands were run locally using ``git version 2.18.0`` (just in case the version of git installed in the container differs).

The only changes (from the version of Squidwarc available on `master`) is in the config (annotated with comments, not valid in JSON)
```
{
  "use": "puppeteer", // new field, specify puppeteer or chrome. puppeteer is required for this functionality    
  "headless": true,
  "script": "./userFns.js", // new field, path to the script to be run for each page crawled
  ....
}
```
If there are any issues with the script or path to the script Squidwarc will inform you.

When checking out Squidwarc like the docker file snippet and simply executing `node index.js -c conf.json` will run the current min working example (uses conf like above).

Of note Squidwarc no longer automatically scrolls the page when a user script is supplied and once the supplied user script resolves WARC generation begins.

If something blows up while testing it (if you do) please let me know here or open new issue (your preference) :smiley:

**Comment by peterk** [comment]
Awesome! Thank you! Will have a look tonight after fishing.

**Comment by N0taN3rd** [comment]
@peterk I would like to keep it to a single script if possible.
One of the nice things about the current scheme is that you have the ability to "concat" `require` additional scripts into the one listed in the config file:

Even though Squidwarc only requires `userFns.js`, that file can require any amount of additional scripts it wishes using node's module system via [require](https://nodejs.org/dist/latest-v10.x/docs/api/modules.html#modules_require) function (commonjs2).

Example:
```js
// contents of userFns.js
const anotherScript = require('./anotherScript') 

module.exports = async function (page) {
   // use anotherScript here 
   await anotherScript(page)
}
```
```js
// contents of anotherScript.js
const fn = require('./moreJs') 

module.exports = async function (page) {
   // use fn here 
   await fn(page)
}
```

This example assumes the files exist on the filesystem like so
```
Squidwarc/
- config.json
- userFns.js
- anotherScript.js
- moreJs.js
```

Any package on npm is available for use here however you must install them along side Squidwarcs dependencies and be able to use them via the [page](https://pptr.dev/#?product=Puppeteer&version=v1.6.2&show=api-class-page) object supplied to the function.

**Comment by peterk** [comment]
I am experimenting with concatenating the required scripts to a job specific js file (that is added to the archive as metadata about what was done to the page). I am new to puppeteer so maybe I am missing something but I can not get scripts to run properly. A small example that replaces the body content:

```javascript
// Test content modification before archiving
module.exports = async function (page) {
  await page.evaluate(() => {
    let dom = document.querySelector('body');
    dom.innerHTML = "<h1>Test of content modification</h1>";
  });
}
```
Or am I missing when the script is actually run in squidwarc with regards to the WARC file creation?

**Comment by N0taN3rd** [comment]
Mutations of the DOM are not "preserved" per say but what is preserved is the HTTP requests for the page and its resources.

However you can take a screenshot of the page after performing such an action (screenshot.png will be created in current working directory)
to see that the mutation is indeed performed.
  
```js
// Test content modification before archiving
module.exports = async function (page) {
  await page.evaluate(() => {
    let dom = document.querySelector('body')
    dom.innerHTML =
      '<h1 style="text-align: center; border: 3px solid green; font-size: 50px">Test of content modification</h1>' 
  })
  await page.screenshot({ path: 'screenshot.png' })
}
```
You can find more information about the page APIs available to you at https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-class-page.

Does this answer your question?

**Comment by peterk** [comment]
Sorry, that was a bad example. I guess I am asking about thinks outside of Squidwarc now, so please let me know if I should take this elsewhere. What I want to do is to run a series of scripts on the page (e.g. expanding comments, scrolling etc) but I fail to get more than one to run. I guess there can only be one module.exports section and I probably need to chain the scripts as per your earlier example.

E.g. in [this page](http://vh216602.truman.edu/agarvey/cs315/ajax/test2.html) I want to click the link and capture the dynamically loaded content with something like this:

```javascript
async function expand_link(page) {
  await page.screenshot({ path: '/archive/screenshot-1.png' });

  const expandLinks = await page.$x("//a[contains(text(), 'Test')]");

  if (expandLinks.length > 0) {
    for (i = 0; i < expandLinks.length; i++) { 
      expandLinks[i].click();
    }
  }

  await page.screenshot({ path: '/archive/screenshot-2.png' });
}

module.exports = async function (page) {
	await expand_link(page);
         //...other function calls for e.g. scrolling etc
}
```

I was expecting that the [dynamically loaded URL in that page](http://vh216602.truman.edu/agarvey/cs315/ajax/target.html) would be archived too, but I am not sure if the click event is fired properly because I can not see it in the warc. Running similar code in plain puppeteer seems to work.

**Comment by peterk** [comment]
And thank you for helping me with everything!

**Comment by N0taN3rd** [comment]
No worries happy to help!

Yes the script Squidwarc executes is expect to only have one `module.exports`, see https://nodejs.org/dist/latest-v10.x/docs/api/modules.html for more info.
Also when performing clicks, like in your example, every action should be `awaited` 
```js
await expandLinks[i].click();
```
unless you do 
```js
await page.evaluate(async function() {
  const iterator = document.evaluate("//a[contains(text(), 'Test')]", document, null, XPathResult.ORDERED_NODE_ITERATOR_TYPE);
  let item;
  while ((item = iterator.iterateNext())) {
    item.click();
  }
})
```
`page.$x` is short hand for above and returns to you an array of element handles, that is to say you will be interacting with those live DOM elements through the dev tools protocol and thus you need to wait (await) for the results of the action to happen.
Again unless you interact with the page / DOM directory though evaluate.

It also does not hurt to through in an default wait period after action or at the very end of scripts 
```js
function delay (time = 5000) {
  return new Promise(resolve => {
    setTimeout(resolve, time)
  })
}

module.exports = async function (page) {
  ...
  await delay() // will wait for 5 seconds
  ...
} 
```

**Comment by peterk** [comment]
I have tried the scripting support for a couple of days now with various websites. It works very well. Spent a lot of time getting the Puppetteer-bundled Chromium to work in a docker image instead of launching a separate Chrome instance. [Warcworker](https://github.com/peterk/warcworker) now has support for user scripts. Thank you for everything!

**Comment by N0taN3rd** [comment]
Awesome! Glad to hear it's working well!

**Comment by N0taN3rd** [comment]
this is implemented
