### ISSUE TITLE
Make option for gzipped WARC:s?

### ISSUE THREAD

**Issue by peterk** [N0taN3rd/Squidwarc#36]
**feature request**: Make option for gzipped WARC:s. 

Not sure if this should be a feature or if users should gzip WARC files outside of Squidwarc/node-warc?

### What is the current behavior?
The WARCS created are currently not gzipped.

**Comment by N0taN3rd** [comment]
Untill I make Squidwarc aware of this (shortly) you can set the env var `NODEWARC_WRITE_GZIPPED` (just needs to exist) and the warcs will be gziped but no `warc.gz` ext
